-- Create the pins table
CREATE TABLE public.pins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  image TEXT NOT NULL,
  "user" TEXT NOT NULL,
  price TEXT NOT NULL
);

-- Set up Row Level Security (RLS) - Optional but recommended
ALTER TABLE public.pins ENABLE ROW LEVEL SECURITY;

-- Allow public read access (anyone can view pins)
CREATE POLICY "Allow public read access" ON public.pins
  FOR SELECT USING (true);

-- Allow authenticated users to insert pins (optional, adjust based on your auth needs)
CREATE POLICY "Allow authenticated insert" ON public.pins
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Allow anon insert for development (WARNING: Disable this in production!)
CREATE POLICY "Allow anon insert" ON public.pins
  FOR INSERT WITH CHECK (true);

-- Insert some dummy data
INSERT INTO public.pins (title, image, "user", price) VALUES
('Mountain View', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4', 'nature_lover', '1200'),
('Abstract Art', 'https://images.unsplash.com/photo-1541701494587-cb58502866ab', 'art_daily', '800'),
('Modern Architecture', 'https://images.unsplash.com/photo-1487958449943-2429e8be8625', 'urban_lens', '1500');

-- Create profiles table
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  website TEXT,

  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- Set up RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function on signup
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
