-- Create the pins table
create table public.pins (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  user_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.pins enable row level security;

-- Policies
create policy "Pins are viewable by everyone." on public.pins
  for select using (true);

create policy "Users can create pins." on public.pins
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own pins." on public.pins
  for delete using (auth.uid() = user_id);
